# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: martin chorley
email: martin.chorley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Dr Martin Chorley. I am a lecturer at the School of Computer Science & Informatics, Cardiff University.I'm programme leader for the MSc in Computational Journalism, and also senior personal tutor for all taught postgraduate students. I mainly do work that falls under the umbrella of the Mobile and Social Computing group.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://martinchorley.co.uk" # the base hostname & protocol for your site

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

twitter_username: martinjc
github_username:  martinjc

site.name: "martinjc.com"

github_repository_url: "martinjc/martinjc.com.git"
github_repository_name: martinjc.com

# Build settings
markdown: kramdown

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']
